### ISSUE TITLE
diffs are sometimes shown even if there is no diff

### ISSUE THREAD

**Issue by grypyrg** [twindb/twindb_table_compare#6]
* TwinDB Table Compare version: develop branch
* Python version: ***
* Operating System: ***

### Description

sometimes a diff is shown even if there is no diff

### What I Did

example output:
```
@@ -31765,10 +31764,0 @@
-3882	2016-04-20 14:57:31
-3882	2016-04-20 14:57:31
-3937	2016-05-13 14:32:53
-3937	2016-03-15 09:47:46
-3542	2016-03-09 12:58:44
-3482	2016-04-01 10:18:11
-3827	2016-03-09 12:58:44
-3827	2016-03-17 16:51:36
-3792	2016-03-15 09:47:47
@@ -31784,0 +31775,10 @@
+3882	2016-04-20 14:57:31
+3882	2016-04-20 14:57:31
+3937	2016-05-13 14:32:53
+3937	2016-03-15 09:47:46
+3542	2016-03-09 12:58:44
+3482	2016-04-01 10:18:11
+3827	2016-03-09 12:58:44
+3827	2016-03-17 16:51:36
+3792	2016-03-15 09:47:47
```

The data is the same, but they were located somewhere else in the diff file.

### Solution

Add an `ORDER BY` primary key in order to remove these false inconsistencies

**Comment by akuzminsky** [comment]
@grypyrg if there are no differences how it happens that this query returns any rows?

```
    query = ("SELECT chunk "
             "FROM `%s`.`%s` "
             "WHERE (this_crc<>master_crc OR this_cnt<>master_cnt) "
             "AND db='%s' AND tbl='%s'")
```

**Comment by grypyrg** [comment]
@akuzminsky: In my case, because there was a valid inconsistency in the same chunk. (but somewhere else)
